### ISSUE TITLE
onChange event triger twice 

### ISSUE THREAD

**Issue by karimahmadi** [pagino/pagino-js#1]
when call pagino.last() or pagino.last() the onChange event triger twice

**Comment by behnammodi** [comment]
@karimahmadi Thanks, I'm on it

**Comment by behnammodi** [comment]
@karimahmadi fixed please update to 1.4.1

**Comment by karimahmadi** [comment]
thnx fixed

**Comment by behnammodi** [comment]
@karimahmadi You're welcome
